# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'SmartHome' do
use_frameworks!

# Pods for ViewCollection

pod 'SnapKit', '~> 4.0.0'
end


